-- liquibase formatted sql

-- changeset pmrodrigues:0044 runOnChange:false
-- comment: Create audit schema and revinfo revision table for Hibernate Envers

CREATE SCHEMA IF NOT EXISTS audit;

CREATE TABLE IF NOT EXISTS audit.revinfo (
    rev         INT4    NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    revtstmp    BIGINT,
    username    VARCHAR(255),
    request_id  VARCHAR(36),
    CONSTRAINT pk_revinfo PRIMARY KEY (rev)
);
