-- liquibase formatted sql

-- changeset pmrodrigues:0045 runOnChange:false
-- comment: Create Hibernate Envers _aud tables for all audited entities (global_with_modified_flag=true)

-- ── security.model ──────────────────────────────────────────────────────────

-- User (password and activation_token are @NotAudited)
CREATE TABLE IF NOT EXISTS audit.users_aud (
    id                          BIGINT  NOT NULL,
    rev                         INT4    NOT NULL,
    revtype                     SMALLINT,
    email                       VARCHAR(255),
    email_mod                   BOOLEAN,
    name                        VARCHAR(255),
    name_mod                    BOOLEAN,
    enabled                     BOOLEAN,
    enabled_mod                 BOOLEAN,
    deleted                     BOOLEAN,
    deleted_mod                 BOOLEAN,
    activation_token_expiry     TIMESTAMP,
    activation_token_expiry_mod BOOLEAN,
    created_at                  TIMESTAMP,
    created_at_mod              BOOLEAN,
    updated_at                  TIMESTAMP,
    updated_at_mod              BOOLEAN,
    CONSTRAINT pk_users_aud     PRIMARY KEY (id, rev),
    CONSTRAINT fk_users_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo(rev)
);

-- User.roles @ElementCollection
CREATE TABLE IF NOT EXISTS audit.user_roles_aud (
    rev                          INT4    NOT NULL,
    revtype                      SMALLINT,
    user_id                      BIGINT  NOT NULL,
    role                         VARCHAR(255),
    CONSTRAINT pk_user_roles_aud PRIMARY KEY (rev, user_id, role),
    CONSTRAINT fk_user_roles_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo(rev)
);

-- User.condominios @ManyToMany
CREATE TABLE IF NOT EXISTS audit.user_condominios_aud (
    rev                              INT4    NOT NULL,
    revtype                          SMALLINT,
    user_id                          BIGINT  NOT NULL,
    condominio_id                    BIGINT  NOT NULL,
    CONSTRAINT pk_user_condominios_aud PRIMARY KEY (rev, user_id, condominio_id),
    CONSTRAINT fk_user_condominios_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo(rev)
);

-- ── commons.model ───────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS audit.estados_aud (
    id                          BIGINT  NOT NULL,
    rev                         INT4    NOT NULL,
    revtype                     SMALLINT,
    nome                        VARCHAR(255),
    nome_mod                    BOOLEAN,
    uf                          VARCHAR(2),
    uf_mod                      BOOLEAN,
    CONSTRAINT pk_estados_aud   PRIMARY KEY (id, rev),
    CONSTRAINT fk_estados_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo(rev)
);

CREATE TABLE IF NOT EXISTS audit.bancos_aud (
    id                          BIGINT  NOT NULL,
    rev                         INT4    NOT NULL,
    revtype                     SMALLINT,
    codigo                      VARCHAR(10),
    codigo_mod                  BOOLEAN,
    nome                        VARCHAR(255),
    nome_mod                    BOOLEAN,
    ispb                        VARCHAR(8),
    ispb_mod                    BOOLEAN,
    deleted                     BOOLEAN,
    deleted_mod                 BOOLEAN,
    created_at                  TIMESTAMP,
    created_at_mod              BOOLEAN,
    updated_at                  TIMESTAMP,
    updated_at_mod              BOOLEAN,
    created_by                  VARCHAR(255),
    created_by_mod              BOOLEAN,
    updated_by                  VARCHAR(255),
    updated_by_mod              BOOLEAN,
    CONSTRAINT pk_bancos_aud    PRIMARY KEY (id, rev),
    CONSTRAINT fk_bancos_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo(rev)
);

-- ── condominio.model ─────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS audit.condominios_aud (
    id                          BIGINT  NOT NULL,
    rev                         INT4    NOT NULL,
    revtype                     SMALLINT,
    nome                        VARCHAR(255),
    nome_mod                    BOOLEAN,
    cnpj                        VARCHAR(18),
    cnpj_mod                    BOOLEAN,
    email                       VARCHAR(255),
    email_mod                   BOOLEAN,
    logradouro                  VARCHAR(255),
    logradouro_mod              BOOLEAN,
    cep                         VARCHAR(8),
    cep_mod                     BOOLEAN,
    cidade                      VARCHAR(255),
    cidade_mod                  BOOLEAN,
    estado_id                   BIGINT,
    estado_id_mod               BOOLEAN,
    deleted                     BOOLEAN,
    deleted_mod                 BOOLEAN,
    created_at                  TIMESTAMP,
    created_at_mod              BOOLEAN,
    updated_at                  TIMESTAMP,
    updated_at_mod              BOOLEAN,
    created_by                  VARCHAR(255),
    created_by_mod              BOOLEAN,
    updated_by                  VARCHAR(255),
    updated_by_mod              BOOLEAN,
    CONSTRAINT pk_condominios_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_condominios_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo(rev)
);

CREATE TABLE IF NOT EXISTS audit.blocos_aud (
    id                          BIGINT  NOT NULL,
    rev                         INT4    NOT NULL,
    revtype                     SMALLINT,
    condominio_id               BIGINT,
    condominio_id_mod           BOOLEAN,
    numero                      INTEGER,
    numero_mod                  BOOLEAN,
    bloco                       VARCHAR(50),
    bloco_mod                   BOOLEAN,
    deleted                     BOOLEAN,
    deleted_mod                 BOOLEAN,
    created_at                  TIMESTAMP,
    created_at_mod              BOOLEAN,
    updated_at                  TIMESTAMP,
    updated_at_mod              BOOLEAN,
    created_by                  VARCHAR(255),
    created_by_mod              BOOLEAN,
    updated_by                  VARCHAR(255),
    updated_by_mod              BOOLEAN,
    CONSTRAINT pk_blocos_aud    PRIMARY KEY (id, rev),
    CONSTRAINT fk_blocos_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo(rev)
);

CREATE TABLE IF NOT EXISTS audit.apartamentos_aud (
    id                          BIGINT  NOT NULL,
    rev                         INT4    NOT NULL,
    revtype                     SMALLINT,
    condominio_id               BIGINT,
    condominio_id_mod           BOOLEAN,
    bloco_id                    BIGINT,
    bloco_id_mod                BOOLEAN,
    numero                      VARCHAR(20),
    numero_mod                  BOOLEAN,
    area_construida             NUMERIC(19,2),
    area_construida_mod         BOOLEAN,
    fracao_ideal                NUMERIC(10,6),
    fracao_ideal_mod            BOOLEAN,
    andar                       INTEGER,
    andar_mod                   BOOLEAN,
    deleted                     BOOLEAN,
    deleted_mod                 BOOLEAN,
    created_at                  TIMESTAMP,
    created_at_mod              BOOLEAN,
    updated_at                  TIMESTAMP,
    updated_at_mod              BOOLEAN,
    created_by                  VARCHAR(255),
    created_by_mod              BOOLEAN,
    updated_by                  VARCHAR(255),
    updated_by_mod              BOOLEAN,
    CONSTRAINT pk_apartamentos_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_apartamentos_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo(rev)
);

-- ── morador.model ────────────────────────────────────────────────────────────

-- Pessoa (abstract JOINED child of User)
CREATE TABLE IF NOT EXISTS audit.pessoas_aud (
    id                          BIGINT  NOT NULL,
    rev                         INT4    NOT NULL,
    revtype                     SMALLINT,
    condominio_id               BIGINT,
    condominio_id_mod           BOOLEAN,
    pessoa_tipo                 VARCHAR(255),
    pessoa_tipo_mod             BOOLEAN,
    apartamento_id              BIGINT,
    apartamento_id_mod          BOOLEAN,
    telefone                    VARCHAR(20),
    telefone_mod                BOOLEAN,
    created_by                  VARCHAR(255),
    created_by_mod              BOOLEAN,
    updated_by                  VARCHAR(255),
    updated_by_mod              BOOLEAN,
    CONSTRAINT pk_pessoas_aud   PRIMARY KEY (id, rev),
    CONSTRAINT fk_pessoas_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo(rev)
);

-- Morador (JOINED child of Pessoa)
CREATE TABLE IF NOT EXISTS audit.moradores_aud (
    id                          BIGINT  NOT NULL,
    rev                         INT4    NOT NULL,
    revtype                     SMALLINT,
    cpf                         VARCHAR(14),
    cpf_mod                     BOOLEAN,
    CONSTRAINT pk_moradores_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_moradores_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo(rev)
);

-- Proprietario (abstract JOINED child of Pessoa — no own scalar columns)
CREATE TABLE IF NOT EXISTS audit.proprietarios_aud (
    id                              BIGINT  NOT NULL,
    rev                             INT4    NOT NULL,
    revtype                         SMALLINT,
    CONSTRAINT pk_proprietarios_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_proprietarios_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo(rev)
);

-- Proprietario.apartamentos @ManyToMany join table
CREATE TABLE IF NOT EXISTS audit.proprietario_apartamentos_aud (
    rev                                      INT4    NOT NULL,
    revtype                                  SMALLINT,
    proprietario_id                          BIGINT  NOT NULL,
    apartamento_id                           BIGINT  NOT NULL,
    CONSTRAINT pk_proprietario_apartamentos_aud PRIMARY KEY (rev, proprietario_id, apartamento_id),
    CONSTRAINT fk_proprietario_apartamentos_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo(rev)
);

-- ProprietarioPessoaFisica (JOINED child of Proprietario)
CREATE TABLE IF NOT EXISTS audit.proprietario_pf_aud (
    id                              BIGINT  NOT NULL,
    rev                             INT4    NOT NULL,
    revtype                         SMALLINT,
    cpf                             VARCHAR(14),
    cpf_mod                         BOOLEAN,
    CONSTRAINT pk_proprietario_pf_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_proprietario_pf_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo(rev)
);

-- ProprietarioPessoaJuridica (JOINED child of Proprietario)
CREATE TABLE IF NOT EXISTS audit.proprietario_pj_aud (
    id                              BIGINT  NOT NULL,
    rev                             INT4    NOT NULL,
    revtype                         SMALLINT,
    cnpj                            VARCHAR(18),
    cnpj_mod                        BOOLEAN,
    razao_social                    VARCHAR(255),
    razao_social_mod                BOOLEAN,
    CONSTRAINT pk_proprietario_pj_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_proprietario_pj_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo(rev)
);

-- ── cobranca.model ───────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS audit.cobrancas_aud (
    id                          BIGINT  NOT NULL,
    rev                         INT4    NOT NULL,
    revtype                     SMALLINT,
    condominio_id               BIGINT,
    condominio_id_mod           BOOLEAN,
    apartamento_id              BIGINT,
    apartamento_id_mod          BOOLEAN,
    cota_rateio_id              BIGINT,
    cota_rateio_id_mod          BOOLEAN,
    morador_id                  BIGINT,
    morador_id_mod              BOOLEAN,
    valor                       NUMERIC(15,2),
    valor_mod                   BOOLEAN,
    vencimento                  DATE,
    vencimento_mod              BOOLEAN,
    status                      VARCHAR(20),
    status_mod                  BOOLEAN,
    asaas_id                    VARCHAR(100),
    asaas_id_mod                BOOLEAN,
    asaas_customer_id           VARCHAR(100),
    asaas_customer_id_mod       BOOLEAN,
    boleto_url                  VARCHAR(500),
    boleto_url_mod              BOOLEAN,
    boleto_codigo_barras        VARCHAR(100),
    boleto_codigo_barras_mod    BOOLEAN,
    pix_qr_code_base64          TEXT,
    pix_qr_code_base64_mod      BOOLEAN,
    pix_copia_cola              VARCHAR(255),
    pix_copia_cola_mod          BOOLEAN,
    email_enviado               BOOLEAN,
    email_enviado_mod           BOOLEAN,
    email_enviado_em            TIMESTAMP,
    email_enviado_em_mod        BOOLEAN,
    pago_em                     TIMESTAMP,
    pago_em_mod                 BOOLEAN,
    deleted                     BOOLEAN,
    deleted_mod                 BOOLEAN,
    created_at                  TIMESTAMP,
    created_at_mod              BOOLEAN,
    updated_at                  TIMESTAMP,
    updated_at_mod              BOOLEAN,
    created_by                  VARCHAR(255),
    created_by_mod              BOOLEAN,
    updated_by                  VARCHAR(255),
    updated_by_mod              BOOLEAN,
    CONSTRAINT pk_cobrancas_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_cobrancas_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo(rev)
);

CREATE TABLE IF NOT EXISTS audit.cobranca_configuracoes_aud (
    id                          BIGINT  NOT NULL,
    rev                         INT4    NOT NULL,
    revtype                     SMALLINT,
    condominio_id               BIGINT,
    condominio_id_mod           BOOLEAN,
    vencimento_dias             INTEGER,
    vencimento_dias_mod         BOOLEAN,
    juros_mora_percent          NUMERIC(5,2),
    juros_mora_percent_mod      BOOLEAN,
    multa_percent               NUMERIC(5,2),
    multa_percent_mod           BOOLEAN,
    descricao_padrao            VARCHAR(255),
    descricao_padrao_mod        BOOLEAN,
    created_at                  TIMESTAMP,
    created_at_mod              BOOLEAN,
    updated_at                  TIMESTAMP,
    updated_at_mod              BOOLEAN,
    created_by                  VARCHAR(255),
    created_by_mod              BOOLEAN,
    updated_by                  VARCHAR(255),
    updated_by_mod              BOOLEAN,
    CONSTRAINT pk_cobranca_configuracoes_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_cobranca_configuracoes_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo(rev)
);

-- ── financeiro.model ─────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS audit.plano_contas_aud (
    id                          BIGINT  NOT NULL,
    rev                         INT4    NOT NULL,
    revtype                     SMALLINT,
    condominio_id               BIGINT,
    condominio_id_mod           BOOLEAN,
    pai_id                      BIGINT,
    pai_id_mod                  BOOLEAN,
    codigo                      VARCHAR(20),
    codigo_mod                  BOOLEAN,
    descricao                   VARCHAR(255),
    descricao_mod               BOOLEAN,
    tipo                        VARCHAR(10),
    tipo_mod                    BOOLEAN,
    tipo_rateio                 VARCHAR(20),
    tipo_rateio_mod             BOOLEAN,
    escopo_rateio               VARCHAR(20),
    escopo_rateio_mod           BOOLEAN,
    deleted                     BOOLEAN,
    deleted_mod                 BOOLEAN,
    created_at                  TIMESTAMP,
    created_at_mod              BOOLEAN,
    updated_at                  TIMESTAMP,
    updated_at_mod              BOOLEAN,
    created_by                  VARCHAR(255),
    created_by_mod              BOOLEAN,
    updated_by                  VARCHAR(255),
    updated_by_mod              BOOLEAN,
    CONSTRAINT pk_plano_contas_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_plano_contas_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo(rev)
);

CREATE TABLE IF NOT EXISTS audit.grupos_despesa_aud (
    id                          BIGINT  NOT NULL,
    rev                         INT4    NOT NULL,
    revtype                     SMALLINT,
    condominio_id               BIGINT,
    condominio_id_mod           BOOLEAN,
    nome                        VARCHAR(255),
    nome_mod                    BOOLEAN,
    tipo_rateio                 VARCHAR(20),
    tipo_rateio_mod             BOOLEAN,
    escopo                      VARCHAR(20),
    escopo_mod                  BOOLEAN,
    bloco_id                    BIGINT,
    bloco_id_mod                BOOLEAN,
    plano_contas_id             BIGINT,
    plano_contas_id_mod         BOOLEAN,
    parametros_json             TEXT,
    parametros_json_mod         BOOLEAN,
    deleted                     BOOLEAN,
    deleted_mod                 BOOLEAN,
    created_at                  TIMESTAMP,
    created_at_mod              BOOLEAN,
    updated_at                  TIMESTAMP,
    updated_at_mod              BOOLEAN,
    created_by                  VARCHAR(255),
    created_by_mod              BOOLEAN,
    updated_by                  VARCHAR(255),
    updated_by_mod              BOOLEAN,
    CONSTRAINT pk_grupos_despesa_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_grupos_despesa_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo(rev)
);

CREATE TABLE IF NOT EXISTS audit.despesas_aud (
    id                          BIGINT  NOT NULL,
    rev                         INT4    NOT NULL,
    revtype                     SMALLINT,
    condominio_id               BIGINT,
    condominio_id_mod           BOOLEAN,
    grupo_despesa_id            BIGINT,
    grupo_despesa_id_mod        BOOLEAN,
    descricao                   VARCHAR(500),
    descricao_mod               BOOLEAN,
    valor_total                 NUMERIC(15,2),
    valor_total_mod             BOOLEAN,
    competencia                 DATE,
    competencia_mod             BOOLEAN,
    rateio_status               VARCHAR(10),
    rateio_status_mod           BOOLEAN,
    data_ultimo_rateio          TIMESTAMP,
    data_ultimo_rateio_mod      BOOLEAN,
    deleted                     BOOLEAN,
    deleted_mod                 BOOLEAN,
    created_at                  TIMESTAMP,
    created_at_mod              BOOLEAN,
    updated_at                  TIMESTAMP,
    updated_at_mod              BOOLEAN,
    created_by                  VARCHAR(255),
    created_by_mod              BOOLEAN,
    updated_by                  VARCHAR(255),
    updated_by_mod              BOOLEAN,
    CONSTRAINT pk_despesas_aud  PRIMARY KEY (id, rev),
    CONSTRAINT fk_despesas_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo(rev)
);

CREATE TABLE IF NOT EXISTS audit.rateio_execucoes_aud (
    id                          BIGINT  NOT NULL,
    rev                         INT4    NOT NULL,
    revtype                     SMALLINT,
    condominio_id               BIGINT,
    condominio_id_mod           BOOLEAN,
    despesa_id                  BIGINT,
    despesa_id_mod              BOOLEAN,
    grupo_despesa_id            BIGINT,
    grupo_despesa_id_mod        BOOLEAN,
    tipo_execucao               VARCHAR(15),
    tipo_execucao_mod           BOOLEAN,
    data_execucao               TIMESTAMP,
    data_execucao_mod           BOOLEAN,
    despesa_total               NUMERIC(15,2),
    despesa_total_mod           BOOLEAN,
    total_unidades              INTEGER,
    total_unidades_mod          BOOLEAN,
    total_cotas                 NUMERIC(15,2),
    total_cotas_mod             BOOLEAN,
    status                      VARCHAR(10),
    status_mod                  BOOLEAN,
    erro_mensagem               TEXT,
    erro_mensagem_mod           BOOLEAN,
    CONSTRAINT pk_rateio_execucoes_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_rateio_execucoes_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo(rev)
);

CREATE TABLE IF NOT EXISTS audit.cotas_rateio_aud (
    id                          BIGINT  NOT NULL,
    rev                         INT4    NOT NULL,
    revtype                     SMALLINT,
    condominio_id               BIGINT,
    condominio_id_mod           BOOLEAN,
    despesa_id                  BIGINT,
    despesa_id_mod              BOOLEAN,
    apartamento_id              BIGINT,
    apartamento_id_mod          BOOLEAN,
    valor                       NUMERIC(15,2),
    valor_mod                   BOOLEAN,
    rateio_execucao_id          BIGINT,
    rateio_execucao_id_mod      BOOLEAN,
    CONSTRAINT pk_cotas_rateio_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_cotas_rateio_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo(rev)
);

CREATE TABLE IF NOT EXISTS audit.coeficientes_rateio_aud (
    id                          BIGINT  NOT NULL,
    rev                         INT4    NOT NULL,
    revtype                     SMALLINT,
    condominio_id               BIGINT,
    condominio_id_mod           BOOLEAN,
    grupo_despesa_id            BIGINT,
    grupo_despesa_id_mod        BOOLEAN,
    apartamento_id              BIGINT,
    apartamento_id_mod          BOOLEAN,
    coeficiente                 NUMERIC(10,6),
    coeficiente_mod             BOOLEAN,
    area_m2                     NUMERIC(8,2),
    area_m2_mod                 BOOLEAN,
    consumo_m3                  NUMERIC(10,3),
    consumo_m3_mod              BOOLEAN,
    vigencia                    DATE,
    vigencia_mod                BOOLEAN,
    deleted                     BOOLEAN,
    deleted_mod                 BOOLEAN,
    created_at                  TIMESTAMP,
    created_at_mod              BOOLEAN,
    created_by                  VARCHAR(255),
    created_by_mod              BOOLEAN,
    CONSTRAINT pk_coeficientes_rateio_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_coeficientes_rateio_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo(rev)
);

CREATE TABLE IF NOT EXISTS audit.orcamento_anual_aud (
    id                          BIGINT  NOT NULL,
    rev                         INT4    NOT NULL,
    revtype                     SMALLINT,
    condominio_id               BIGINT,
    condominio_id_mod           BOOLEAN,
    exercicio                   INTEGER,
    exercicio_mod               BOOLEAN,
    status                      VARCHAR(15),
    status_mod                  BOOLEAN,
    taxa_estimada_unidade       NUMERIC(15,2),
    taxa_estimada_unidade_mod   BOOLEAN,
    deleted                     BOOLEAN,
    deleted_mod                 BOOLEAN,
    created_at                  TIMESTAMP,
    created_at_mod              BOOLEAN,
    updated_at                  TIMESTAMP,
    updated_at_mod              BOOLEAN,
    created_by                  VARCHAR(255),
    created_by_mod              BOOLEAN,
    updated_by                  VARCHAR(255),
    updated_by_mod              BOOLEAN,
    CONSTRAINT pk_orcamento_anual_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_orcamento_anual_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo(rev)
);

CREATE TABLE IF NOT EXISTS audit.item_orcamento_aud (
    id                          BIGINT  NOT NULL,
    rev                         INT4    NOT NULL,
    revtype                     SMALLINT,
    condominio_id               BIGINT,
    condominio_id_mod           BOOLEAN,
    orcamento_anual_id          BIGINT,
    orcamento_anual_id_mod      BOOLEAN,
    plano_contas_id             BIGINT,
    plano_contas_id_mod         BOOLEAN,
    valor_previsto              NUMERIC(15,2),
    valor_previsto_mod          BOOLEAN,
    valor_realizado             NUMERIC(15,2),
    valor_realizado_mod         BOOLEAN,
    deleted                     BOOLEAN,
    deleted_mod                 BOOLEAN,
    created_at                  TIMESTAMP,
    created_at_mod              BOOLEAN,
    updated_at                  TIMESTAMP,
    updated_at_mod              BOOLEAN,
    CONSTRAINT pk_item_orcamento_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_item_orcamento_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo(rev)
);

CREATE TABLE IF NOT EXISTS audit.contas_bancarias_aud (
    id                          BIGINT  NOT NULL,
    rev                         INT4    NOT NULL,
    revtype                     SMALLINT,
    condominio_id               BIGINT,
    condominio_id_mod           BOOLEAN,
    banco_id                    BIGINT,
    banco_id_mod                BOOLEAN,
    tipo                        VARCHAR(15),
    tipo_mod                    BOOLEAN,
    agencia                     VARCHAR(10),
    agencia_mod                 BOOLEAN,
    conta                       VARCHAR(20),
    conta_mod                   BOOLEAN,
    digito                      VARCHAR(2),
    digito_mod                  BOOLEAN,
    descricao                   VARCHAR(255),
    descricao_mod               BOOLEAN,
    chave_pix                   VARCHAR(255),
    chave_pix_mod               BOOLEAN,
    saldo_contabil              NUMERIC(15,2),
    saldo_contabil_mod          BOOLEAN,
    ativa                       BOOLEAN,
    ativa_mod                   BOOLEAN,
    deleted                     BOOLEAN,
    deleted_mod                 BOOLEAN,
    created_at                  TIMESTAMP,
    created_at_mod              BOOLEAN,
    updated_at                  TIMESTAMP,
    updated_at_mod              BOOLEAN,
    created_by                  VARCHAR(255),
    created_by_mod              BOOLEAN,
    updated_by                  VARCHAR(255),
    updated_by_mod              BOOLEAN,
    CONSTRAINT pk_contas_bancarias_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_contas_bancarias_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo(rev)
);

CREATE TABLE IF NOT EXISTS audit.lancamentos_bancarios_aud (
    id                          BIGINT  NOT NULL,
    rev                         INT4    NOT NULL,
    revtype                     SMALLINT,
    condominio_id               BIGINT,
    condominio_id_mod           BOOLEAN,
    conta_bancaria_id           BIGINT,
    conta_bancaria_id_mod       BOOLEAN,
    data_lancamento             DATE,
    data_lancamento_mod         BOOLEAN,
    valor                       NUMERIC(15,2),
    valor_mod                   BOOLEAN,
    tipo                        VARCHAR(10),
    tipo_mod                    BOOLEAN,
    descricao                   VARCHAR(500),
    descricao_mod               BOOLEAN,
    origem                      VARCHAR(30),
    origem_mod                  BOOLEAN,
    referencia_id               BIGINT,
    referencia_id_mod           BOOLEAN,
    status                      VARCHAR(15),
    status_mod                  BOOLEAN,
    deleted                     BOOLEAN,
    deleted_mod                 BOOLEAN,
    created_at                  TIMESTAMP,
    created_at_mod              BOOLEAN,
    updated_at                  TIMESTAMP,
    updated_at_mod              BOOLEAN,
    created_by                  VARCHAR(255),
    created_by_mod              BOOLEAN,
    updated_by                  VARCHAR(255),
    updated_by_mod              BOOLEAN,
    CONSTRAINT pk_lancamentos_bancarios_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_lancamentos_bancarios_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo(rev)
);

CREATE TABLE IF NOT EXISTS audit.fundo_reserva_aud (
    id                          BIGINT  NOT NULL,
    rev                         INT4    NOT NULL,
    revtype                     SMALLINT,
    condominio_id               BIGINT,
    condominio_id_mod           BOOLEAN,
    percentual_arrecadacao      NUMERIC(5,2),
    percentual_arrecadacao_mod  BOOLEAN,
    saldo_atual                 NUMERIC(15,2),
    saldo_atual_mod             BOOLEAN,
    conta_bancaria_id           BIGINT,
    conta_bancaria_id_mod       BOOLEAN,
    deleted                     BOOLEAN,
    deleted_mod                 BOOLEAN,
    created_at                  TIMESTAMP,
    created_at_mod              BOOLEAN,
    updated_at                  TIMESTAMP,
    updated_at_mod              BOOLEAN,
    created_by                  VARCHAR(255),
    created_by_mod              BOOLEAN,
    updated_by                  VARCHAR(255),
    updated_by_mod              BOOLEAN,
    CONSTRAINT pk_fundo_reserva_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_fundo_reserva_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo(rev)
);

CREATE TABLE IF NOT EXISTS audit.fundo_reserva_movimentacao_aud (
    id                          BIGINT  NOT NULL,
    rev                         INT4    NOT NULL,
    revtype                     SMALLINT,
    condominio_id               BIGINT,
    condominio_id_mod           BOOLEAN,
    fundo_reserva_id            BIGINT,
    fundo_reserva_id_mod        BOOLEAN,
    tipo                        VARCHAR(10),
    tipo_mod                    BOOLEAN,
    valor                       NUMERIC(15,2),
    valor_mod                   BOOLEAN,
    justificativa               TEXT,
    justificativa_mod           BOOLEAN,
    data_movimentacao           DATE,
    data_movimentacao_mod       BOOLEAN,
    deleted                     BOOLEAN,
    deleted_mod                 BOOLEAN,
    created_at                  TIMESTAMP,
    created_at_mod              BOOLEAN,
    updated_at                  TIMESTAMP,
    updated_at_mod              BOOLEAN,
    CONSTRAINT pk_fundo_reserva_movimentacao_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_fundo_reserva_movimentacao_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo(rev)
);

CREATE TABLE IF NOT EXISTS audit.extrato_importacoes_aud (
    id                          BIGINT  NOT NULL,
    rev                         INT4    NOT NULL,
    revtype                     SMALLINT,
    condominio_id               BIGINT,
    condominio_id_mod           BOOLEAN,
    conta_bancaria_id           BIGINT,
    conta_bancaria_id_mod       BOOLEAN,
    formato                     VARCHAR(10),
    formato_mod                 BOOLEAN,
    data_importacao             TIMESTAMP,
    data_importacao_mod         BOOLEAN,
    data_inicio                 DATE,
    data_inicio_mod             BOOLEAN,
    data_fim                    DATE,
    data_fim_mod                BOOLEAN,
    total_itens                 INTEGER,
    total_itens_mod             BOOLEAN,
    itens_conciliados           INTEGER,
    itens_conciliados_mod       BOOLEAN,
    itens_pendentes             INTEGER,
    itens_pendentes_mod         BOOLEAN,
    status                      VARCHAR(15),
    status_mod                  BOOLEAN,
    mensagem_erro               VARCHAR(255),
    mensagem_erro_mod           BOOLEAN,
    nome_arquivo                VARCHAR(500),
    nome_arquivo_mod            BOOLEAN,
    deleted                     BOOLEAN,
    deleted_mod                 BOOLEAN,
    created_at                  TIMESTAMP,
    created_at_mod              BOOLEAN,
    updated_at                  TIMESTAMP,
    updated_at_mod              BOOLEAN,
    created_by                  VARCHAR(255),
    created_by_mod              BOOLEAN,
    updated_by                  VARCHAR(255),
    updated_by_mod              BOOLEAN,
    CONSTRAINT pk_extrato_importacoes_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_extrato_importacoes_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo(rev)
);

CREATE TABLE IF NOT EXISTS audit.itens_extrato_aud (
    id                          BIGINT  NOT NULL,
    rev                         INT4    NOT NULL,
    revtype                     SMALLINT,
    condominio_id               BIGINT,
    condominio_id_mod           BOOLEAN,
    extrato_importacao_id       BIGINT,
    extrato_importacao_id_mod   BOOLEAN,
    lancamento_id               BIGINT,
    lancamento_id_mod           BOOLEAN,
    item_orcamento_id           BIGINT,
    item_orcamento_id_mod       BOOLEAN,
    data_lancamento             DATE,
    data_lancamento_mod         BOOLEAN,
    valor                       NUMERIC(15,2),
    valor_mod                   BOOLEAN,
    tipo                        VARCHAR(10),
    tipo_mod                    BOOLEAN,
    descricao                   VARCHAR(500),
    descricao_mod               BOOLEAN,
    numero_documento            VARCHAR(100),
    numero_documento_mod        BOOLEAN,
    status                      VARCHAR(15),
    status_mod                  BOOLEAN,
    deleted                     BOOLEAN,
    deleted_mod                 BOOLEAN,
    created_at                  TIMESTAMP,
    created_at_mod              BOOLEAN,
    updated_at                  TIMESTAMP,
    updated_at_mod              BOOLEAN,
    CONSTRAINT pk_itens_extrato_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_itens_extrato_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo(rev)
);

-- ── gateway.model ────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS audit.asaas_customers_aud (
    id                          BIGINT  NOT NULL,
    rev                         INT4    NOT NULL,
    revtype                     SMALLINT,
    pessoa_id                   BIGINT,
    pessoa_id_mod               BOOLEAN,
    customer_id                 VARCHAR(100),
    customer_id_mod             BOOLEAN,
    created_at                  TIMESTAMP,
    created_at_mod              BOOLEAN,
    CONSTRAINT pk_asaas_customers_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_asaas_customers_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo(rev)
);
