name: CICD Project

on:
  push:
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-


      - name: Build with Maven
        run: mvn clean install --no-transfer-progress

      - name: Run unit tests
        run: mvn test --no-transfer-progress  # Isso força a execução dos testes se não forem executados com o package

      - name: Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'
          detailed_summary: true
          include_passed: true
  e2e-tests:
      runs-on: ubuntu-latest
      depends_on: unit-tests
      steps:
        - name: Run unit tests
          run: mvn verify -Pe2e --no-transfer-progress

        - name: Test Report
          uses: mikepenz/action-junit-report@v4
          if: success() || failure()
          with:
            report_paths: '**/target/cucumber-reports/index.html'
            detailed_summary: true
            include_passed: true# Isso força a execução dos testes se não forem executados com o package
  jacoco-report:
    runs-on: ubuntu-latest
    needs: [unit-tests, e2e-tests]
    steps:
      - name: Upload Jacoco Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: '**/target/site/jacoco-resources/jacoco.xml'
          detailed_summary: true
          include_passed: true# Isso força a execução dos testes se não forem executados com o package